import { AiInterface } from "../interfaces/ai.interfaces";


import { OpenAI } from "openai";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(__dirname, '../../../.env') });

class GroqProvider implements AiInterface {

    async chat(messages: Array<any>, apiKey?: string): Promise<Array<object>> {
        const client = new OpenAI({
            apiKey: apiKey || process.env.GROA_AI_API,
            baseURL: "https://api.groq.com/openai/v1",
        });

        const fallbackModels = [
            "qwen/qwen3-32b",
            "meta-llama/llama-4-scout-17b-16e-instruct",
            "qwen-2.5-coder-32b",
            "llama-3.3-70b-versatile",
            "llama-3.1-8b-instant"
        ];

        let lastError: any = null;

        // Keep system prompt at index 0, and slice the rest to max 5 messages
        const optimizedMessages = messages.length > 6
            ? [messages[0], ...messages.slice(1).slice(-5)]
            : messages;

        for (const model of fallbackModels) {
            try {
                const response: any = await client.chat.completions.create({
                    model: model,
                    messages: optimizedMessages,
                    max_tokens: 1024,
                    temperature: 0.7,
                });

                let content = response.choices[0].message.content;

                // Remove <think> blocks generated by reasoning models
                content = content.replace(/<think>[\s\S]*?<\/think>/g, '');

                // Clean up trailing dashes and empty lines
                content = content.replace(/(\n\s*-\s*)*$/g, '');
                content = content.replace(/-+$/g, '');

                return content.trim();
            } catch (error: any) {
                console.log(`[GroqProvider] Model ${model} failed, switching to next model...`);
                console.error(model, error);
                lastError = error;
            }
        }

        throw new Error(`All Groq models failed. Last error: ${lastError?.message}`);
    }
}


export { GroqProvider };
